language: python
python:
  - "3.6"

# nbformat is needed to run the tests
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip python3-mysqldb
  - sudo pip3 install -U pip


install:
  - pip3 install -U jupyter
  - pip3 install -U nbformat
  - pip3 install -r binder/requirements.txt
script:
  - jupyter nbconvert --to notebook --execute session1/A5-Inserting_Data_in_MySQL_using_Python.ipynb
  - jupyter nbconvert --to notebook --execute session1/A6-Inserting_Data_in_MySQL_using_PythonPandas.ipynb
